server:
  port: 8080
  servlet:
    session:
      persistence: false
      timeout: 0

management:
  security.enabled: false
  endpoints.web.exposure.include:
    - prometheus
    - health
    - metrics
    - shutdown

spring:
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  application:
    admin:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

